<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>Flowa.DatadogMetrics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DatadogMetrics.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\flowa.commons\Commons.csproj" />
  </ItemGroup>

</Project>
