<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>OrderAccumulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flowa.Shared\Flowa.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
